name: 'Deploy to Firebase Functions'
author: 'Waveblur <prachayawut.s@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Functions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'blue'
